---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctf-challenge-operator
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.ctf.backbone81
    resources:
      - apikeys
      - challengeinstances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.ctf.backbone81
    resources:
      - apikeys/finalizers
      - challengeinstances/finalizers
    verbs:
      - update
  - apiGroups:
      - core.ctf.backbone81
    resources:
      - apikeys/status
      - challengeinstances/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.ctf.backbone81
    resources:
      - challengedescriptions
    verbs:
      - get
      - list
      - watch
