---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctf-challenge-operator-deny-all
  namespace: ctf-challenge-operator
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
