---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctf-challenge-operator
  namespace: ctf-challenge-operator
  labels:
    app.kubernetes.io/name: ctf-challenge-operator
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
