---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-challenge-operator
  namespace: ctf-challenge-operator
  labels:
    app.kubernetes.io/name: ctf-challenge-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-challenge-operator
subjects:
  - kind: ServiceAccount
    name: ctf-challenge-operator
    namespace: ctf-challenge-operator
