# This rule is not used by the project ctf-challenge-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.ctf.backbone81.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ctf-challenge-operator
    app.kubernetes.io/managed-by: kustomize
  name: apikey-admin-role
rules:
- apiGroups:
  - core.ctf.backbone81
  resources:
  - apikeys
  verbs:
  - '*'
- apiGroups:
  - core.ctf.backbone81
  resources:
  - apikeys/status
  verbs:
  - get
