---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.ctf.backbone81
  resources:
  - apikeys
  - challengedescriptions
  - challengeinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.ctf.backbone81
  resources:
  - apikeys/finalizers
  - challengedescriptions/finalizers
  - challengeinstances/finalizers
  verbs:
  - update
- apiGroups:
  - core.ctf.backbone81
  resources:
  - apikeys/status
  - challengedescriptions/status
  - challengeinstances/status
  verbs:
  - get
  - patch
  - update
