apiVersion: core.ctf.backbone81/v1alpha1
kind: ChallengeInstance
metadata:
  labels:
    app.kubernetes.io/name: ctf-challenge-operator
    app.kubernetes.io/managed-by: kustomize
  name: challengeinstance-sample
spec:
  # TODO(user): Add fields here
