---
apiVersion: core.ctf.backbone81/v1alpha1
kind: ChallengeDescription
metadata:
  name: challenge-description-sample
spec:
  title: Demo Challenge
  description: This is a demo challenge.
  category: Web exploitation
  value: 100
  hints:
    - description: This is some hint.
      cost: 10
  flag: CTF{TestFlag}
  manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: demo-challenge
        namespace: default
        labels:
          app.kubernetes.io/name: demo-challenge
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: demo-challenge
        template:
          metadata:
            labels:
              app.kubernetes.io/name: demo-challenge
          spec:
            containers:
              - name: httpd
                image: httpd:2.4
