name: Renovate

on:
  schedule:
    - cron: '0 9 * * SAT'
  # This trigger is for debug purposes right now.
  push:

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.1
        with:
          configurationFile: scripts/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
