name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Tests
        run: |
          set -ex
          export PATH=${PWD}/bin:${PATH}
          etcd --version
          kube-apiserver --version
          kubectl --version
          make test

      - name: Check Generated Files
        run: |
          set -ex
          git diff
